# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2022_CvDI_Hw1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 790)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoadImage = QtWidgets.QGroupBox(self.centralwidget)
        self.LoadImage.setGeometry(QtCore.QRect(40, 130, 221, 361))
        self.LoadImage.setObjectName("LoadImage")
        self.LoadFolder = QtWidgets.QPushButton(self.LoadImage)
        self.LoadFolder.setGeometry(QtCore.QRect(40, 80, 93, 28))
        self.LoadFolder.setObjectName("LoadFolder")
        self.LoadImage_L = QtWidgets.QPushButton(self.LoadImage)
        self.LoadImage_L.setGeometry(QtCore.QRect(40, 120, 93, 28))
        self.LoadImage_L.setObjectName("LoadImage_L")
        self.LoadImageR = QtWidgets.QPushButton(self.LoadImage)
        self.LoadImageR.setGeometry(QtCore.QRect(40, 160, 93, 28))
        self.LoadImageR.setObjectName("LoadImageR")
        self.Calibration = QtWidgets.QGroupBox(self.centralwidget)
        self.Calibration.setGeometry(QtCore.QRect(280, 110, 211, 431))
        self.Calibration.setObjectName("Calibration")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Calibration)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 180, 181, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.ShowResult = QtWidgets.QPushButton(self.groupBox_3)
        self.ShowResult.setGeometry(QtCore.QRect(20, 170, 131, 28))
        self.ShowResult.setObjectName("ShowResult")
        self.FindDisortion = QtWidgets.QPushButton(self.groupBox_3)
        self.FindDisortion.setGeometry(QtCore.QRect(20, 120, 131, 31))
        self.FindDisortion.setObjectName("FindDisortion")
        self.FindExtrinsic = QtWidgets.QPushButton(self.groupBox_3)
        self.FindExtrinsic.setGeometry(QtCore.QRect(20, 80, 131, 28))
        self.FindExtrinsic.setObjectName("FindExtrinsic")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 80, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.FindCorner = QtWidgets.QPushButton(self.Calibration)
        self.FindCorner.setGeometry(QtCore.QRect(20, 60, 131, 28))
        self.FindCorner.setObjectName("FindCorner")
        self.FindIntrinsic = QtWidgets.QPushButton(self.Calibration)
        self.FindIntrinsic.setGeometry(QtCore.QRect(20, 120, 131, 28))
        self.FindIntrinsic.setObjectName("FindIntrinsic")
        self.AugementedReality = QtWidgets.QGroupBox(self.centralwidget)
        self.AugementedReality.setGeometry(QtCore.QRect(520, 110, 281, 421))
        self.AugementedReality.setObjectName("AugementedReality")
        self.ShowWordsonBoard = QtWidgets.QPushButton(self.AugementedReality)
        self.ShowWordsonBoard.setGeometry(QtCore.QRect(30, 130, 201, 31))
        self.ShowWordsonBoard.setObjectName("ShowWordsonBoard")
        self.ShowWordsonVertically = QtWidgets.QPushButton(self.AugementedReality)
        self.ShowWordsonVertically.setGeometry(QtCore.QRect(30, 210, 201, 31))
        self.ShowWordsonVertically.setObjectName("ShowWordsonVertically")
        self.lineEdit = QtWidgets.QLineEdit(self.AugementedReality)
        self.lineEdit.setGeometry(QtCore.QRect(30, 60, 121, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.SteroDisparityMap = QtWidgets.QGroupBox(self.centralwidget)
        self.SteroDisparityMap.setGeometry(QtCore.QRect(830, 110, 231, 421))
        self.SteroDisparityMap.setObjectName("SteroDisparityMap")
        self.SteroDisparity = QtWidgets.QPushButton(self.SteroDisparityMap)
        self.SteroDisparity.setGeometry(QtCore.QRect(20, 170, 201, 31))
        self.SteroDisparity.setObjectName("SteroDisparity")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoadImage.setTitle(_translate("MainWindow", "Load Image"))
        self.LoadFolder.setText(_translate("MainWindow", "Load Folder"))
        self.LoadImage_L.setText(_translate("MainWindow", "Load Image_L"))
        self.LoadImageR.setText(_translate("MainWindow", "Load Image_R"))
        self.Calibration.setTitle(_translate("MainWindow", "1.Calibration  "))
        self.groupBox_3.setTitle(_translate("MainWindow", "1.3 Find extrinsic"))
        self.ShowResult.setText(_translate("MainWindow", "1.5 Show Result"))
        self.FindDisortion.setText(_translate("MainWindow", "1.4 Find Distortion"))
        self.FindExtrinsic.setText(_translate("MainWindow", "1.3 Find Extrinsic "))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "15"))
        self.FindCorner.setText(_translate("MainWindow", "1.1 Find Corner"))
        self.FindIntrinsic.setText(_translate("MainWindow", "1,2 Find Intrinsic "))
        self.AugementedReality.setTitle(_translate("MainWindow", "2.Augemented Reality"))
        self.ShowWordsonBoard.setText(_translate("MainWindow", "2.1 Show Words on Board"))
        self.ShowWordsonVertically.setText(_translate("MainWindow", "2.2 Show Words on Vertically"))
        self.SteroDisparityMap.setTitle(_translate("MainWindow", "3.Stereo Disparity Map"))
        self.SteroDisparity.setText(_translate("MainWindow", "3.1 Stereo Disparity Map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

